// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package tiff

import (
	"image"
	"image/color"
	"reflect"
)

type imageGrayA64f struct {
	M struct {
		Pix    []uint8
		Stride int
		Rect   image.Rectangle
	}
}

// newImageGrayA64f returns a new imageGrayA64f with the given bounds.
func newImageGrayA64f(r image.Rectangle) *imageGrayA64f {
	return new(imageGrayA64f).Init(make([]uint8, 8*r.Dx()*r.Dy()), 8*r.Dx(), r)
}

func (p *imageGrayA64f) Init(pix []uint8, stride int, rect image.Rectangle) *imageGrayA64f {
	*p = imageGrayA64f{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *imageGrayA64f) Pix() []byte           { return p.M.Pix }
func (p *imageGrayA64f) Stride() int           { return p.M.Stride }
func (p *imageGrayA64f) Rect() image.Rectangle { return p.M.Rect }
func (p *imageGrayA64f) Channels() int         { return 2 }
func (p *imageGrayA64f) Depth() reflect.Kind   { return reflect.Float32 }

func (p *imageGrayA64f) ColorModel() color.Model { return colorGrayA64fModel }

func (p *imageGrayA64f) Bounds() image.Rectangle { return p.M.Rect }

func (p *imageGrayA64f) At(x, y int) color.Color {
	return p.GrayA64fAt(x, y)
}

func (p *imageGrayA64f) GrayA64fAt(x, y int) colorGrayA64f {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorGrayA64f{}
	}
	i := p.PixOffset(x, y)
	return pGrayA64fAt(p.M.Pix[i:])
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *imageGrayA64f) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*8
}

func (p *imageGrayA64f) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := colorGrayA64fModel.Convert(c).(colorGrayA64f)
	pSetGrayA64f(p.M.Pix[i:], c1)
	return
}

func (p *imageGrayA64f) SetGrayA64f(x, y int, c colorGrayA64f) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	pSetGrayA64f(p.M.Pix[i:], c)
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *imageGrayA64f) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &imageGrayA64f{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(imageGrayA64f).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *imageGrayA64f) Opaque() bool {
	if p.M.Rect.Empty() {
		return true
	}
	for y := p.M.Rect.Min.Y; y < p.M.Rect.Max.Y; y++ {
		for x := p.M.Rect.Min.X; x < p.M.Rect.Max.X; x++ {
			if _, _, _, a := p.At(x, y).RGBA(); a == 0xFFFF {
				return false
			}
		}
	}
	return true
}
