// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package tiff

import (
	"image"
	"image/color"
	"reflect"
)

type imageGray struct {
	M struct {
		Pix    []uint8
		Stride int
		Rect   image.Rectangle
	}
}

// newImageGray returns a new imageGray with the given bounds.
func newImageGray(r image.Rectangle) *imageGray {
	return new(imageGray).Init(make([]uint8, 1*r.Dx()*r.Dy()), 1*r.Dx(), r)
}

func (p *imageGray) Init(pix []uint8, stride int, rect image.Rectangle) *imageGray {
	*p = imageGray{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *imageGray) Pix() []byte           { return p.M.Pix }
func (p *imageGray) Stride() int           { return p.M.Stride }
func (p *imageGray) Rect() image.Rectangle { return p.M.Rect }
func (p *imageGray) Channels() int         { return 1 }
func (p *imageGray) Depth() reflect.Kind   { return reflect.Uint8 }

func (p *imageGray) ColorModel() color.Model { return colorGrayModel }

func (p *imageGray) Bounds() image.Rectangle { return p.M.Rect }

func (p *imageGray) At(x, y int) color.Color {
	return p.GrayAt(x, y)
}

func (p *imageGray) GrayAt(x, y int) colorGray {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorGray{}
	}
	i := p.PixOffset(x, y)
	return pGrayAt(p.M.Pix[i:])
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *imageGray) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*1
}

func (p *imageGray) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := colorGrayModel.Convert(c).(colorGray)
	pSetGray(p.M.Pix[i:], c1)
	return
}

func (p *imageGray) SetGray(x, y int, c colorGray) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	pSetGray(p.M.Pix[i:], c)
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *imageGray) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &imageGray{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(imageGray).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *imageGray) Opaque() bool {
	return true
}
