// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package tiff

import (
	"image"
	"image/color"
	"reflect"
)

type GrayA32 struct {
	M struct {
		Pix    []uint8
		Stride int
		Rect   image.Rectangle
	}
}

// NewGrayA32 returns a new GrayA32 with the given bounds.
func NewGrayA32(r image.Rectangle) *GrayA32 {
	return new(GrayA32).Init(make([]uint8, 4*r.Dx()*r.Dy()), 4*r.Dx(), r)
}

func (p *GrayA32) Init(pix []uint8, stride int, rect image.Rectangle) *GrayA32 {
	*p = GrayA32{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *GrayA32) Pix() []byte           { return p.M.Pix }
func (p *GrayA32) Stride() int           { return p.M.Stride }
func (p *GrayA32) Rect() image.Rectangle { return p.M.Rect }
func (p *GrayA32) Channels() int         { return 2 }
func (p *GrayA32) Depth() reflect.Kind   { return reflect.Uint16 }

func (p *GrayA32) ColorModel() color.Model { return colorGrayA32Model }

func (p *GrayA32) Bounds() image.Rectangle { return p.M.Rect }

func (p *GrayA32) At(x, y int) color.Color {
	return p.GrayA32At(x, y)
}

func (p *GrayA32) GrayA32At(x, y int) colorGrayA32 {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorGrayA32{}
	}
	i := p.PixOffset(x, y)
	return pGrayA32At(p.M.Pix[i:])
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *GrayA32) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*4
}

func (p *GrayA32) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := colorGrayA32Model.Convert(c).(colorGrayA32)
	pSetGrayA32(p.M.Pix[i:], c1)
	return
}

func (p *GrayA32) SetGrayA32(x, y int, c colorGrayA32) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	pSetGrayA32(p.M.Pix[i:], c)
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *GrayA32) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &GrayA32{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(GrayA32).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *GrayA32) Opaque() bool {
	if p.M.Rect.Empty() {
		return true
	}
	for y := p.M.Rect.Min.Y; y < p.M.Rect.Max.Y; y++ {
		for x := p.M.Rect.Min.X; x < p.M.Rect.Max.X; x++ {
			if _, _, _, a := p.At(x, y).RGBA(); a == 0xFFFF {
				return false
			}
		}
	}
	return true
}
