// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package tiff

import (
	"image"
	"image/color"
	"reflect"
)

type imageRGB struct {
	M struct {
		Pix    []uint8
		Stride int
		Rect   image.Rectangle
	}
}

// newImageRGB returns a new imageRGB with the given bounds.
func newImageRGB(r image.Rectangle) *imageRGB {
	return new(imageRGB).Init(make([]uint8, 3*r.Dx()*r.Dy()), 3*r.Dx(), r)
}

func (p *imageRGB) Init(pix []uint8, stride int, rect image.Rectangle) *imageRGB {
	*p = imageRGB{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *imageRGB) Pix() []byte           { return p.M.Pix }
func (p *imageRGB) Stride() int           { return p.M.Stride }
func (p *imageRGB) Rect() image.Rectangle { return p.M.Rect }
func (p *imageRGB) Channels() int         { return 3 }
func (p *imageRGB) Depth() reflect.Kind   { return reflect.Uint8 }

func (p *imageRGB) ColorModel() color.Model { return colorRGBModel }

func (p *imageRGB) Bounds() image.Rectangle { return p.M.Rect }

func (p *imageRGB) At(x, y int) color.Color {
	return p.RGBAt(x, y)
}

func (p *imageRGB) RGBAt(x, y int) colorRGB {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorRGB{}
	}
	i := p.PixOffset(x, y)
	return pRGBAt(p.M.Pix[i:])
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *imageRGB) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*3
}

func (p *imageRGB) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := colorRGBModel.Convert(c).(colorRGB)
	pSetRGB(p.M.Pix[i:], c1)
	return
}

func (p *imageRGB) SetRGB(x, y int, c colorRGB) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	pSetRGB(p.M.Pix[i:], c)
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *imageRGB) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &imageRGB{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(imageRGB).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *imageRGB) Opaque() bool {
	return true
}
