// Copyright 2014 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

package tiff

import (
	"image"
	"image/color"
	"reflect"
)

type Gray32f struct {
	M struct {
		Pix    []uint8
		Stride int
		Rect   image.Rectangle
	}
}

// NewGray32f returns a new Gray32f with the given bounds.
func NewGray32f(r image.Rectangle) *Gray32f {
	return new(Gray32f).Init(make([]uint8, 4*r.Dx()*r.Dy()), 4*r.Dx(), r)
}

func (p *Gray32f) Init(pix []uint8, stride int, rect image.Rectangle) *Gray32f {
	*p = Gray32f{
		M: struct {
			Pix    []uint8
			Stride int
			Rect   image.Rectangle
		}{
			Pix:    pix,
			Stride: stride,
			Rect:   rect,
		},
	}
	return p
}

func (p *Gray32f) Pix() []byte           { return p.M.Pix }
func (p *Gray32f) Stride() int           { return p.M.Stride }
func (p *Gray32f) Rect() image.Rectangle { return p.M.Rect }
func (p *Gray32f) Channels() int         { return 1 }
func (p *Gray32f) Depth() reflect.Kind   { return reflect.Float32 }

func (p *Gray32f) ColorModel() color.Model { return colorGray32fModel }

func (p *Gray32f) Bounds() image.Rectangle { return p.M.Rect }

func (p *Gray32f) At(x, y int) color.Color {
	return p.Gray32fAt(x, y)
}

func (p *Gray32f) Gray32fAt(x, y int) colorGray32f {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return colorGray32f{}
	}
	i := p.PixOffset(x, y)
	return pGray32fAt(p.M.Pix[i:])
}

// PixOffset returns the index of the first element of Pix that corresponds to
// the pixel at (x, y).
func (p *Gray32f) PixOffset(x, y int) int {
	return (y-p.M.Rect.Min.Y)*p.M.Stride + (x-p.M.Rect.Min.X)*4
}

func (p *Gray32f) Set(x, y int, c color.Color) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	c1 := colorGray32fModel.Convert(c).(colorGray32f)
	pSetGray32f(p.M.Pix[i:], c1)
	return
}

func (p *Gray32f) SetGray32f(x, y int, c colorGray32f) {
	if !(image.Point{x, y}.In(p.M.Rect)) {
		return
	}
	i := p.PixOffset(x, y)
	pSetGray32f(p.M.Pix[i:], c)
	return
}

// SubImage returns an image representing the portion of the image p visible
// through r. The returned value shares pixels with the original image.
func (p *Gray32f) SubImage(r image.Rectangle) image.Image {
	r = r.Intersect(p.M.Rect)
	// If r1 and r2 are Rectangles, r1.Intersect(r2) is not guaranteed to be inside
	// either r1 or r2 if the intersection is empty. Without explicitly checking for
	// this, the Pix[i:] expression below can panic.
	if r.Empty() {
		return &Gray32f{}
	}
	i := p.PixOffset(r.Min.X, r.Min.Y)
	return new(Gray32f).Init(
		p.M.Pix[i:],
		p.M.Stride,
		r,
	)
}

// Opaque scans the entire image and reports whether it is fully opaque.
func (p *Gray32f) Opaque() bool {
	return true
}
